/// Flutter icons CustonIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustonIcons
///      fonts:
///       - asset: fonts/CustonIcons.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class CustonIcons {
  CustonIcons._();

  static const _kFontFam = 'CustonIcons';
  static const String? _kFontPkg = null;

  static const IconData chrome = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
